//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("ShellTools")]
[assembly: System.Reflection.AssemblyProduct("ShellTools")]
[assembly: System.Reflection.AssemblyDescription("Tools for Windows Shell")]
[assembly: System.Reflection.AssemblyCompany("LoreSoft")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © 2014 LoreSoft")]
[assembly: System.Runtime.InteropServices.Guid("db20169e-3c64-4649-85e2-9233ad45b474")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyConfiguration("Release")]
[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.0.0.0")]



internal sealed partial class ThisAssembly {
    
    internal const string AssemblyTitle = "ShellTools";
    
    internal const string AssemblyProduct = "ShellTools";
    
    internal const string AssemblyDescription = "Tools for Windows Shell";
    
    internal const string AssemblyCompany = "LoreSoft";
    
    internal const string AssemblyCopyright = "Copyright © 2014 LoreSoft";
    
    internal const string Guid = "db20169e-3c64-4649-85e2-9233ad45b474";
    
    internal const string AssemblyConfiguration = "Release";
    
    internal const string AssemblyVersion = "1.0.0.0";
    
    internal const string AssemblyFileVersion = "1.0.0.0";
    
    internal const string AssemblyInformationalVersion = "1.0.0.0";
    
    private ThisAssembly() {
    }
}
